(() => {
  'use strict';
  const W=1280,H=720,STORE='sffc13-state-v1';
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const canvas=$('#gameCanvas'), ctx=canvas.getContext('2d');
  const screens={menu:$('#menu'),select:$('#select'),settings:$('#settings'),pause:$('#pause'),result:$('#result')};
  const hud=$('#hud'), dashBtn=$('#dashBtn'), marker=$('#game-state-marker');
  const tr={ru:{badge:'Neon Candy Space Nursery',title:'Космический кот ловит еду',subtitle:'Уворачивайся от бомб, собирай космо-лакомства и открывай 10 питомцев.',play:'Играть',animals:'Животные',settings:'Настройки',controlsHint:'WASD/стрелки или перетаскивание пальцем. Space — рывок.',selectTitle:'Выбор питомца',startRun:'Старт',back:'Назад',sound:'Звук',motion:'Частицы и тряска',english:'English UI',reset:'Сброс прогресса',paused:'Пауза',resume:'Продолжить',restart:'Заново',menu:'Меню',result:'Результат',again:'Ещё раз'},en:{badge:'Neon Candy Space Nursery',title:'Space Cat Food Catcher',subtitle:'Dodge bombs, collect space treats and unlock 10 pets.',play:'Play',animals:'Animals',settings:'Settings',controlsHint:'WASD/arrows or touch-drag. Space — dash.',selectTitle:'Choose pet',startRun:'Start',back:'Back',sound:'Sound',motion:'Particles and shake',english:'English UI',reset:'Reset progress',paused:'Paused',resume:'Resume',restart:'Restart',menu:'Menu',result:'Result',again:'Again'}};
  const animals=[['cat_astronaut','Кот','Cat',1,'balanced'],['giraffe_bubble_helmet','Жираф','Giraffe',2,'food +18%'],['shark_mini_spacesuit','Акула','Shark',3,'fast X'],['crocodile_jetpack','Крокодил','Crocodile',4,'shield'],['panda_antigrav_cushion','Панда','Panda',5,'long shield'],['fox_comet_tail','Лиса','Fox',6,'combo'],['penguin_ice_spacesuit','Пингвин','Penguin',7,'brake'],['raccoon_engineer_backpack','Енот','Raccoon',8,'stars'],['rabbit_moon_ears','Кролик','Rabbit',9,'dash'],['owl_stargazer','Сова','Owl',10,'warning']].map(a=>({id:a[0],ru:a[1],en:a[2],unlock:a[3],trait:a[4]}));
  const sizes={cat_astronaut:[56,56,21],giraffe_bubble_helmet:[64,64,24],shark_mini_spacesuit:[58,44,22],crocodile_jetpack:[62,46,23],panda_antigrav_cushion:[60,60,23],fox_comet_tail:[58,50,22],penguin_ice_spacesuit:[56,56,21],raccoon_engineer_backpack:[58,54,22],rabbit_moon_ears:[60,62,22],owl_stargazer:[58,58,22],space_bomb_basic:[44,44,18],satellite_mine:[48,48,20],asteroid_shard:[34,34,13],boss_wave_bomb:[76,76,32],star_food:[34,34,18],shield_capsule:[38,38,19],magnet_satellite:[38,38,19],heart_pickup:[36,36,18],star_currency:[30,30,15]};
  const fallback={background:{nebula_playfield:'assets/background/nebula_playfield.png',menu_planet_window:'assets/background/menu_planet_window.png',character_select_hangar:'assets/background/character_select_hangar.png'},player:Object.fromEntries(animals.map(a=>[a.id,`assets/player/${a.id}.png`])),hazard:{space_bomb_basic:'assets/hazard/space_bomb_basic.png',satellite_mine:'assets/hazard/satellite_mine.png',boss_wave_bomb:'assets/hazard/boss_wave_bomb.png',laser_warning_beam:'assets/hazard/laser_warning_beam.png'},obstacle:{asteroid_shard:'assets/obstacle/asteroid_shard.png'},collectable:{star_food:'assets/collectable/star_food.png',heart_pickup:'assets/collectable/heart_pickup.png',star_currency:'assets/collectable/star_currency.png'},powerup:{shield_capsule:'assets/powerup/shield_capsule.png',magnet_satellite:'assets/powerup/magnet_satellite.png'}};
  const audioPaths={ui:'assets/audio/kenney_digital-audio/Audio/pepSound1.ogg',pick:'assets/audio/kenney_digital-audio/Audio/powerUp1.ogg',hit:'assets/audio/kenney_sci-fi-sounds/Audio/impactMetal_000.ogg',dash:'assets/audio/kenney_sci-fi-sounds/Audio/thrusterFire_000.ogg',shield:'assets/audio/kenney_sci-fi-sounds/Audio/forceField_000.ogg',win:'assets/audio/kenney_music-jingles/Audio/8-Bit jingles/jingles_NES00.ogg'};
  let manifest=fallback, imgs={}, audio={}, dpr=1, scale=1, ox=0, oy=0, last=0, state='menu', raf=0;
  let save=loadSave(), keys={}, pointer=null, objects=[], particles=[], lasers=[], shake=0;
  let player, score=0, xpGain=0, combo=1, lives=3, shield=0, magnet=0, inv=0, dashCd=0, time=0, spawn=0, pickupSpawn=0;
  function loadSave(){try{return Object.assign({level:1,xp:0,best:0,selected:'cat_astronaut',lang:'ru',sound:true,motion:true},JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return {level:1,xp:0,best:0,selected:'cat_astronaut',lang:'ru',sound:true,motion:true}}}
  function persist(){localStorage.setItem(STORE,JSON.stringify(save))}
  async function boot(){resize(); addEventListener('resize',resize); bindUI(); applyLang(); await loadManifest(); loadImages(); loadAudio(); buildCards(); show('menu'); requestAnimationFrame(loop)}
  async function loadManifest(){if(location.protocol==='file:'){manifest=fallback;return} try{const [r,o]=await Promise.all([fetch('data/raster-asset-map.json').then(x=>x.json()),fetch('data/object-size-map.json').then(x=>x.json())]); manifest=normalize(r); Object.entries(o.objects||{}).forEach(([k,v])=>{const st=v.states&&v.states.idle;if(st)sizes[k]=[st.display_width,st.display_height,(st.hitbox&& (st.hitbox.radius||st.hitbox.radius_x))||20]})}catch(e){manifest=fallback;console.info('Manifest fallback for local launch',e&&e.message?e.message:'unavailable')}}
  function normalize(map){const out=JSON.parse(JSON.stringify(fallback)); Object.values(map.assets||{}).flat().forEach(a=>{const p=a.still_path||a.spritesheet_path||a.reference_path;if(!p)return; (out[a.role]||(out[a.role]={}))[a.id]=p}); return out}
  function loadImages(){const paths={...manifest.background,...manifest.player,...manifest.hazard,...manifest.obstacle,...manifest.collectable,...manifest.powerup}; Object.entries(paths).forEach(([id,path])=>{const im=new Image(); im.src=path; imgs[id]=im})}
  function loadAudio(){Object.entries(audioPaths).forEach(([k,p])=>{const a=new Audio(p); a.preload='auto'; audio[k]=a})}
  function snd(k){if(!save.sound||!audio[k])return; try{const a=audio[k].cloneNode(); a.volume=.35; a.play().catch(()=>{})}catch{}}
  function resize(){dpr=Math.min(devicePixelRatio||1,2); canvas.width=innerWidth*dpr; canvas.height=innerHeight*dpr; canvas.style.width=innerWidth+'px'; canvas.style.height=innerHeight+'px'; ctx.setTransform(dpr,0,0,dpr,0,0); scale=Math.min(innerWidth/W,innerHeight/H); ox=(innerWidth-W*scale)/2; oy=(innerHeight-H*scale)/2}
  const sx=x=>ox+x*scale, sy=y=>oy+y*scale, sw=n=>n*scale, mx=x=>(x-ox)/scale, my=y=>(y-oy)/scale;
  function show(s){state=s; Object.values(screens).forEach(e=>e.classList.remove('active')); if(screens[s])screens[s].classList.add('active'); hud.classList.toggle('hidden',s!=='play'); dashBtn.classList.toggle('hidden',s!=='play'); if(s==='select')buildCards(); updateMarkers(); snd('ui')}
  function applyLang(){const pack=tr[save.lang]; $$('[data-i18n]').forEach(e=>e.textContent=pack[e.dataset.i18n]||e.textContent); $('#langToggle').checked=save.lang==='en'; $('#soundToggle').checked=save.sound; $('#motionToggle').checked=save.motion; document.documentElement.lang=save.lang}
  function bindUI(){ $('#playBtn').onclick=start; $('#animalsBtn').onclick=()=>show('select'); $('#settingsBtn').onclick=()=>show('settings'); $('#startBtn').onclick=start; $('#pauseBtn').onclick=()=>show('pause'); $('#resumeBtn').onclick=()=>show('play'); $('#restartBtn').onclick=start; $('#againBtn').onclick=start; $('#soundToggle').onchange=e=>{save.sound=e.target.checked;persist()}; $('#motionToggle').onchange=e=>{save.motion=e.target.checked;persist()}; $('#langToggle').onchange=e=>{save.lang=e.target.checked?'en':'ru';applyLang();buildCards();persist();updateMarkers()}; $('#resetBtn').onclick=()=>{localStorage.removeItem(STORE);save=loadSave();applyLang();buildCards();updateMarkers()}; $$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go)); addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' '){e.preventDefault();dash()} if(e.key==='p'||e.key==='Escape')show(state==='play'?'pause':'play')}); addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false); canvas.addEventListener('pointerdown',touch); canvas.addEventListener('pointermove',touch); canvas.addEventListener('pointerup',()=>pointer=null); dashBtn.onclick=dash }
  function buildCards(){const c=$('#cards'); c.innerHTML=''; animals.forEach(a=>{const locked=save.level<a.unlock, el=document.createElement('button'); el.className='card '+(locked?'locked ':'')+(save.selected===a.id?'selected':''); el.innerHTML=`<img src="assets/player/${a.id}.png" alt=""><b>${save.lang==='en'?a.en:a.ru}</b><small>${locked?'Lv '+a.unlock:a.trait}</small>`; el.onclick=()=>{if(!locked){save.selected=a.id;persist();buildCards();}}; c.appendChild(el)})}
  function touch(e){if(state!=='play')return; pointer={x:mx(e.clientX),y:my(e.clientY)}; e.preventDefault()}
  function start(){const a=animals.find(x=>x.id===save.selected)||animals[0], sz=sizes[a.id]||[56,56,21]; player={id:a.id,x:W/2,y:H-120,vx:0,vy:0,r:sz[2],w:sz[0],h:sz[1],speed:410}; if(a.id.includes('shark'))player.speed=440; if(a.id.includes('panda'))player.speed=382; lives=a.id.includes('crocodile')?3:3; shield=a.id.includes('crocodile')?1:0; score=0; xpGain=0; combo=1; magnet=0; inv=1; dashCd=0; time=0; spawn=0; pickupSpawn=1; objects=[]; particles=[]; lasers=[]; show('play')}
  function dash(){if(state!=='play'||dashCd>0)return; const dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0), dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0); const l=Math.hypot(dx,dy)||1; const mul=player.id.includes('rabbit')?1.15:1; player.x+=dx/l*122*mul; player.y+=dy/l*122*mul; clampPlayer(); dashCd=player.id.includes('rabbit')?2.8:3.8; burst(player.x,player.y,'#4efff1',12); snd('dash')}
  function loop(t){const dt=Math.min((t-last)/1000||0,0.033); last=t; update(dt); draw(); raf=requestAnimationFrame(loop)}
  function update(dt){if(state!=='play')return; time+=dt; inv=Math.max(0,inv-dt); dashCd=Math.max(0,dashCd-dt); magnet=Math.max(0,magnet-dt); move(dt); spawners(dt); updateObjects(dt); particles=particles.filter(p=>(p.t-=dt)>0); particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt}); updateHud()}
  function move(dt){let ax=0,ay=0; if(keys.a||keys.arrowleft)ax--; if(keys.d||keys.arrowright)ax++; if(keys.w||keys.arrowup)ay--; if(keys.s||keys.arrowdown)ay++; if(pointer){player.x+=(pointer.x-player.x)*Math.min(1,dt*7); player.y+=(pointer.y-player.y)*Math.min(1,dt*7)} else {const l=Math.hypot(ax,ay)||1; player.vx=(player.vx+ax/l*player.speed*dt*6)*.86; player.vy=(player.vy+ay/l*player.speed*dt*6)*.86; player.x+=player.vx*dt; player.y+=player.vy*dt} clampPlayer()}
  function clampPlayer(){player.x=Math.max(30,Math.min(W-30,player.x)); player.y=Math.max(86,Math.min(H-30,player.y))}
  function spawners(dt){const diff=1+time/55+save.level*.045; spawn-=dt; pickupSpawn-=dt; if(spawn<=0){spawn=Math.max(.18,.72/diff); spawnHazard(diff)} if(pickupSpawn<=0){pickupSpawn=1.35+Math.random()*1.3; spawnPickup()} if(time>14&&Math.random()<dt*.11) spawnLaser()}
  function spawnHazard(diff){const roll=Math.random(); let type=roll>.92?'boss_wave_bomb':roll>.62?'satellite_mine':roll>.34?'asteroid_shard':'space_bomb_basic'; const sz=sizes[type], side=Math.random(); let x=Math.random()*W,y=-50,vx=(Math.random()-.5)*90,vy=(type==='asteroid_shard'?270:type==='boss_wave_bomb'?145:type==='satellite_mine'?170:215)*diff; if(side>.72){x=Math.random()<.5?-50:W+50;y=120+Math.random()*420;vx=(x<0?1:-1)*(140+80*Math.random())*diff;vy=(Math.random()-.3)*100} objects.push({kind:'hazard',type,x,y,vx,vy,r:sz[2],w:sz[0],h:sz[1],a:Math.random()*6,t:0})}
  function spawnPickup(){const types=['star_food','star_currency','shield_capsule','magnet_satellite','heart_pickup']; const type=types[Math.random()<.58?0:Math.floor(Math.random()*types.length)]; const sz=sizes[type]; objects.push({kind:'pickup',type,x:40+Math.random()*(W-80),y:-30,vx:(Math.random()-.5)*35,vy:90+Math.random()*80,r:sz[2],w:sz[0],h:sz[1],t:0})}
  function spawnLaser(){const x=80+Math.random()*(W-160); lasers.push({x,t:0,warn:(animals.find(a=>a.id===player.id)?.id==='owl_stargazer')?1.0:.72,active:.28,done:false})}
  function updateObjects(dt){objects.forEach(o=>{o.t+=dt;if(o.type==='satellite_mine')o.x+=Math.sin(o.t*4)*38*dt;o.x+=o.vx*dt;o.y+=o.vy*dt;if(o.kind==='pickup'&&magnet>0){const dx=player.x-o.x,dy=player.y-o.y,d=Math.hypot(dx,dy); if(d<210){o.x+=dx/d*250*dt;o.y+=dy/d*250*dt}} if(hit(o)){o.kind==='hazard'?damage(o):collect(o); o.dead=true}}); objects=objects.filter(o=>!o.dead&&o.y<H+100&&o.x>-120&&o.x<W+120); lasers.forEach(l=>{l.t+=dt;if(l.t>l.warn&&l.t<l.warn+l.active&&Math.abs(player.x-l.x)<18&&inv<=0)damage({x:l.x,y:player.y,type:'laser'}); if(l.t>l.warn+l.active)l.done=true}); lasers=lasers.filter(l=>!l.done)}
  function hit(o){const d=Math.hypot(player.x-o.x,player.y-o.y); return d<player.r+o.r}
  function collect(o){let val=o.type==='star_food'?90:o.type==='shield_capsule'?140:o.type==='heart_pickup'?80:110; if(player.id.includes('giraffe')&&o.type==='star_food')val*=1.18; score+=Math.round(val*combo); xpGain+=o.type==='star_food'?5:8; combo=Math.min(9.9,combo+.15*(player.id.includes('fox')?1.25:1)); if(o.type==='shield_capsule'){shield++;snd('shield')} if(o.type==='magnet_satellite')magnet=7; if(o.type==='heart_pickup')lives=Math.min(4,lives+1); burst(o.x,o.y,'#ffe45e',10); snd('pick')}
  function damage(o){if(inv>0)return; if(shield>0){shield--;inv=1;burst(player.x,player.y,'#4efff1',16);snd('shield');return} lives--; combo=1; inv=1.15; shake=.18; burst(player.x,player.y,'#ff3d5a',18); snd('hit'); if(lives<=0)endRun()}
  function endRun(){save.best=Math.max(save.best,score); const old=save.level; save.xp+=Math.round(xpGain+score/80+time*1.2); while(save.level<10&&save.xp>=need(save.level)){save.xp-=need(save.level);save.level++} persist(); const unlocked=save.level>old?animals.filter(a=>a.unlock>old&&a.unlock<=save.level).map(a=>save.lang==='en'?a.en:a.ru).join(', '):''; $('#resultText').textContent=(save.lang==='en'?`Score ${score}. Best ${save.best}. XP +${Math.round(xpGain)}.`:`Счёт ${score}. Рекорд ${save.best}. XP +${Math.round(xpGain)}.`)+(unlocked?(save.lang==='en'?` Unlocked: ${unlocked}!`:` Открыто: ${unlocked}!`):''); show('result'); snd('win')}
  function need(l){return 120+l*l*55}
  function updateHud(){$('#score').textContent=score|0; $('#level').textContent=save.level; $('#hearts').textContent='♥'.repeat(Math.max(0,lives)); $('#combo').textContent='x'+combo.toFixed(1); $('#shield').textContent='◇'+shield; $('#xpbar').style.width=Math.min(100,save.xp/need(save.level)*100)+'%'; updateMarkers()}
  function updateMarkers(){const live=state==='play'; document.body.dataset.gameState=state; document.body.dataset.score=String(score|0); document.body.dataset.time=String(time.toFixed(1)); document.body.dataset.level=String(save.level); if(marker)marker.textContent=`State ${state} Score ${score|0} Time ${time.toFixed(1)} Level ${save.level} Lives ${lives}${live?' Playing':''}`}
  function burst(x,y,c,n){if(!save.motion)return; for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*240,vy:(Math.random()-.5)*240,t:.35+Math.random()*.35,c})}
  function draw(){ctx.clearRect(0,0,innerWidth,innerHeight); const sh=save.motion?shake:0; if(shake>0)shake-=.016; ctx.save(); ctx.translate((Math.random()-.5)*sh*22,(Math.random()-.5)*sh*22); bg(); if(state==='play'||state==='pause'||state==='result'){lasers.forEach(drawLaser); objects.forEach(drawObj); drawPlayer(); particles.forEach(drawParticle)} ctx.restore()}
  function bg(){const bg=imgs.nebula_playfield; if(bg&&bg.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,innerWidth,innerHeight); else {const g=ctx.createRadialGradient(innerWidth*.2,innerHeight*.1,0,innerWidth*.5,innerHeight*.5,innerWidth);g.addColorStop(0,'#32165f');g.addColorStop(1,'#070a22');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight)} ctx.fillStyle='rgba(116,247,255,.9)'; for(let i=0;i<70;i++){const x=(i*173+time*18)%W,y=(i*97)%H;ctx.globalAlpha=.25+(i%5)*.12;ctx.fillRect(sx(x),sy(y),sw(2),sw(2))} ctx.globalAlpha=1}
  function drawImg(id,x,y,w,h,rot=0){const im=imgs[id]; ctx.save(); ctx.translate(sx(x),sy(y)); ctx.rotate(rot); if(im&&im.complete&&im.naturalWidth)ctx.drawImage(im,-sw(w)/2,-sw(h)/2,sw(w),sw(h)); else fallbackShape(id,w,h); ctx.restore()}
  function fallbackShape(id,w,h){ctx.shadowBlur=14;ctx.shadowColor=id.includes('bomb')||id.includes('mine')?'#ff3d5a':'#74f7ff';ctx.fillStyle=id.includes('bomb')||id.includes('mine')?'#2b193a':id.includes('heart')?'#ff6fae':id.includes('shield')?'#4efff1':'#ffe45e';ctx.beginPath(); if(id.includes('asteroid')){for(let i=0;i<7;i++){const a=i/7*Math.PI*2,r=sw((i%2?18:12));ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}} else ctx.arc(0,0,sw(Math.max(w,h)/2),0,7);ctx.fill();ctx.shadowBlur=0}
  function drawObj(o){drawImg(o.type,o.x,o.y,o.w,o.h,o.a+o.t); if(o.kind==='hazard'){ctx.strokeStyle='rgba(255,61,90,.35)';ctx.lineWidth=sw(2);ctx.beginPath();ctx.arc(sx(o.x),sy(o.y),sw(o.r+5+Math.sin(time*8)*3),0,7);ctx.stroke()}}
  function drawPlayer(){if(!player)return; if(shield>0||inv>0){ctx.strokeStyle=shield>0?'#4efff1':'#ff70d6';ctx.lineWidth=sw(4);ctx.beginPath();ctx.arc(sx(player.x),sy(player.y),sw(player.r+12+Math.sin(time*9)*3),0,7);ctx.stroke()} drawImg(player.id,player.x,player.y+Math.sin(time*4)*3,player.w,player.h,Math.max(-.28,Math.min(.28,player.vx/900)))}
  function drawLaser(l){const active=l.t>l.warn; ctx.save();ctx.globalAlpha=active?0.88:0.25+Math.sin(time*24)*.18;ctx.strokeStyle=active?'#ff3d5a':'#ffe45e';ctx.lineWidth=sw(active?18:6);ctx.setLineDash(active?[]:[sw(16),sw(12)]);ctx.beginPath();ctx.moveTo(sx(l.x),sy(80));ctx.lineTo(sx(l.x),sy(H));ctx.stroke();ctx.restore()}
  function drawParticle(p){ctx.globalAlpha=Math.max(0,p.t*2);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),sw(3+p.t*4),0,7);ctx.fill();ctx.globalAlpha=1}
  boot();
})();
